Implement Unit Test #8
akdcstar/ProjectComments pull request #10
Opened 2018-02-16 10:44 UTC by akdcstar

2018-02-16 15:07 UTC, extsoft commented
@akdcstar please merge or rebase latest master into this branch. And solve a conflict with the Selenium dependency.

2018-02-16 15:52 UTC, akdcstar commented
@extsoft I've merged current branch with origin/master, please check.

2018-02-16 16:12 UTC, extsoft commented
> @extsoft I've merged current branch with origin/master, please check.

@akdcstar great!

2018-02-16 16:15 UTC, extsoft requested changes
@akdcstar Please pay attention to the comments below.

2018-02-16 16:15 UTC, extsoft commented on src/test/java/net/comments/sample/AttentiveStudentTest.java
> +}
Please add an empty line at the end of the file.

2018-02-16 16:15 UTC, extsoft commented on src/test/java/net/comments/sample/BadStudentTest.java
> +}
Please add an empty line at the end of the file.

2018-02-16 16:15 UTC, extsoft commented on src/test/java/net/comments/sample/LimitedRoomTest.java
> +        List<Person> personList = new ArrayList<Person>();
Why didn't you use `LimitedRoom` class here?

2018-02-16 16:15 UTC, extsoft commented on src/test/java/net/comments/sample/SubjectCookingTest.java
> +}
Please add an empty line at the end of the file.

2018-02-16 16:15 UTC, extsoft commented on src/test/java/net/comments/sample/SubjectGitTest.java
> +}
Please add an empty line at the end of the file.

2018-02-16 16:15 UTC, extsoft commented on src/test/java/net/comments/sample/TechTeacherTest.java
> +}
Please add an empty line at the end of the file.

2018-02-16 16:15 UTC, extsoft commented on src/test/java/net/comments/sample/UnlimitedRoomTest.java
> +public class UnlimitedRoomTest {
Why `UnlimitedRoom` is not used in the test?

2018-02-19 15:54 UTC, akdcstar commented
@extsoft I've fixed all your comments

2018-02-19 19:43 UTC, extsoft approved these changes
@akdcstar look's great!

2018-02-19 19:43 UTC, merged